[build-system]
requires = [ "setuptools>=77", "setuptools-scm",]
build-backend = "setuptools.build_meta"

[project]
name = "arches-controlled-lists"
version = "1.2.0a0"
description = "An Arches application designed to manage controlled lists and reference data within the Arches platform."
readme = "README.md"
requires-python = ">=3.12"
license = "AGPL-3.0-or-later"
license-files = [ "LICENSE",]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: Django",
    "Framework :: Django :: 5.2",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [ "arches>=8.2.0a1", "arches-component-lab>=0.0.1a11",]
dynamic = []

[[project.authors]]
name = "Arches Project"

[project.urls]
Homepage = "https://archesproject.org/"
Documentation = "https://arches.readthedocs.io"
Repository = "https://github.com/archesproject/arches-controlled-lists.git"
Issues = "https://github.com/archesproject/arches-controlled-lists/issues"

[tool.setuptools]
packages = [ "arches_controlled_lists",]

[dependency-groups]
dev = [ "livereload", "sst", "coverage", "django-silk==5.3.2", "pre-commit", "black==24.4.2",]
